# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: AlpaslanBek.Promptline
PackageVersion: 0.2.22
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ProductCode: Promptline
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bekalpaslan/promptline/releases/download/v0.2.22/Promptline_0.2.22_x64-setup.exe
  InstallerSha256: 038D0B9A9C1D760BDF0756703A82F3ED02A46292E0A094A7FE5D91A581D21C3C
ManifestType: installer
ManifestVersion: 1.10.0
