# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: AlpaslanBek.Promptline
PackageVersion: 0.2.18
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ProductCode: Promptline
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bekalpaslan/promptline/releases/download/v0.2.18/Promptline_0.2.18_x64-setup.exe
  InstallerSha256: E8BB2DEFDD1097D9B7B349C503BF9DAF67EFABA6F043EF19F4651CD9B84105B8
ManifestType: installer
ManifestVersion: 1.10.0
